insert into `groups`(`GroupKey`,`GroupId`,`GroupName`) values ('_GenKey_',5,'Pencatat Surat');
alter table `tb_setting` add column `versi` varchar(15) NULL after `nama_instansi`;
alter table `classification` add column `RetensiThn_Active` int(2) DEFAULT NULL after `ClDesc`, add column `RetensiThn_InActive` int(2) DEFAULT NULL after `RetensiThn_Active`;
alter table `inbox` add column `Tesaurus` varchar(150) NULL after `NAgenda`;
alter table `inbox` change `NId` `NId` varchar(100) NOT NULL comment 'Naskah ID';
alter table `inbox` change `CreationRoleId` `CreationRoleId` varchar(250) NOT NULL;
alter table `inbox` change `Instansipengirim` `Instansipengirim` varchar(150) NOT NULL;
alter table `inbox` change `Namapengirim` `Namapengirim` varchar(150) NOT NULL;
alter table `inbox_receiver` change `NId` `NId` varchar(100) default '0' NOT NULL comment 'Naskah ID';
alter table `inbox_receiver` change `GIR_Id` `GIR_Id` varchar(20) default '0' NOT NULL comment 'Group ID';
alter table `inbox_receiver` change `RoleId_From` `RoleId_From` varchar(250) NOT NULL comment;
alter table `inbox_receiver` change `RoleId_To` `RoleId_To` varchar(250) NOT NULL comment;
alter table `inbox_files` change `NId` `NId` varchar(100) default '0' NOT NULL comment 'Naskah ID';
alter table `inbox_files` change `GIR_Id` `GIR_Id` varchar(20) character set latin1 collate latin1_swedish_ci default '0' NOT NULL comment 'Group ID', drop primary key;
alter table `inbox_files` change `PeopleRoleID` `PeopleRoleID` varchar(250) NOT NULL;
alter table `inbox_reference` change `NId` `NId` varchar(100) default '0' NOT NULL comment 'Naskah ID';
alter table `inbox_reference` change `Id_Ref` `Id_Ref` varchar(100) default '0' NOT NULL comment 'Ref ID';
alter table `role` add column `gjabatanId` varchar(14) NOT NULL after `RoleStatus`;
alter table `people` change `PeopleUsername` `PeopleUsername` varchar(40) NOT NULL;
alter table `people` add column `RoleAtasan` varchar(250) NOT NULL after `GroupId`;
drop table if exists `master_instansi`;
CREATE TABLE `master_instansi` ( `id` int(11) NOT NULL AUTO_INCREMENT, `kode_instansi` varchar(35) DEFAULT NULL, `nama_instansi` varchar(250) DEFAULT NULL, `nama_resmi` varchar(250) DEFAULT NULL, `tipe_instansi` varchar(250) DEFAULT NULL, `tgl` date, `fungsi` varchar(250) DEFAULT NULL, `mandat` varchar(250) DEFAULT NULL, `status_instansi` varchar(2) DEFAULT NULL, `creation_by` varchar(15) DEFAULT NULL, `created_date` datetime DEFAULT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
drop table if exists `chat`;
CREATE TABLE `chat` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT, `from` varchar(255) NOT NULL DEFAULT '', `to` varchar(255) NOT NULL DEFAULT '', `message` text NOT NULL, PRIMARY KEY (`id`), KEY `to` (`to`), KEY `from` (`from`)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
drop table if exists `master_btn`;
CREATE TABLE `master_btn` (`btn_key` varchar(15) NOT NULL, `btn_func` varchar(10) DEFAULT NULL, `btn_text` varchar(35) DEFAULT NULL, `btn_desc` varchar(100) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;
insert into `master_btn` (`btn_key`,`btn_func`,`btn_text`,`btn_desc`) values ('_GenKey_.1','balas','Nota Dinas','Tombol untuk Nota Dinas'),('_GenKey_.2','teruskan','Teruskan','Tombol untuk Meneruskan (Forward)'),('_GenKey_.3','disposisi','Disposisi','Tombol untuk Disposisi'),('_GenKey_.4','usul','Nota Dinas','Tombol untuk Memberi Nota Dinas Usulan'),('_GenKey_.5','ubah','Ubah Metadata','Tombol untuk Ubah Metadata'),('_GenKey_.6','final','Upload Surat Final','Tombol untuk Surat Final'),('_GenKey_.7','kembali','Kembali','Tombol untuk Kembali'),('_GenKey_.8','closed','Tutup Berkas','Tombol untuk Menutup Berkas');
insert into `master_report_name`(`VitId`,`VitName`) values ('_GenKey_.13','Laporan arsip Berdasarkan Petugas Registrasi');
drop table if exists `peoplesession`;
CREATE TABLE `peoplesession` ( `SessionKey` varchar(15) DEFAULT NULL, `PeopleId` int(11) DEFAULT NULL, `SessionId` varchar(25) DEFAULT NULL, `OnlineSince` datetime DEFAULT NULL, `IPAddress` varchar(25) DEFAULT NULL, KEY `FK_peoplesession` (`SessionKey`,`PeopleId`), CONSTRAINT `FK_peoplesession` FOREIGN KEY (`SessionKey`, `PeopleId`) REFERENCES `people` (`PeopleKey`, `PeopleId`)) ENGINE=InnoDB DEFAULT CHARSET=latin1 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;
DROP TABLE IF EXISTS `master_color`;
CREATE TABLE `master_color` (`CKey` varchar(12) default NULL, `CUsed` varchar(12) default NULL, `Color` varchar(7) default NULL, `CDesc` varchar(50) default NULL) ENGINE=MyISAM DEFAULT CHARSET=latin1 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;
insert  into `master_color`(`CKey`,`CUsed`,`Color`,`CDesc`) values ('_GenKey_','to','#a5ee75','Digunakan Untuk Surat Yang Belum Dibuka');
CREATE TABLE `master_doc_template` ( `doc_id` varchar(50) NOT NULL, `doc_desc` varchar(250) DEFAULT NULL, `doc_file` varchar(250) DEFAULT NULL, `upload_date` datetime DEFAULT NULL, PRIMARY KEY (`doc_id`) ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
update classification set RetensiThn_Active = 0 where RetensiThn_Active is null;
update classification set RetensiThn_InActive = 0 where RetensiThn_InActive is null;
alter table `classification` add column `SusutId` varchar(14) NOT NULL after `RetensiThn_InActive`;
delete from inbox_files where FileName_real = '';
alter table `inbox_receiver` add column `To_Id_Desc` varchar(150) NULL after `ReceiveDate`;
update inbox_receiver r set r.To_Id_Desc = (select rr.RoleName from role rr where rr.RoleId = r.RoleId_To);
drop table if exists `master_disposisi`;
CREATE TABLE `master_disposisi` (`DisposisiId` varchar(14) NOT NULL,`DisposisiName` varchar(100) NOT NULL, `gjabatanId` varchar(14) NOT NULL, PRIMARY KEY (`DisposisiId`)) ENGINE=InnoDB DEFAULT CHARSET=latin1 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;
CREATE TABLE `master_gjabatan` (`gjabatanId` varchar(14) NOT NULL,`gjabatanName` varchar(50) NOT NULL,  PRIMARY KEY (`gjabatanId`)) ENGINE=InnoDB DEFAULT CHARSET=latin1 CHECKSUM=1 DELAY_KEY_WRITE=1 ROW_FORMAT=DYNAMIC;
CREATE TABLE `inbox_disposisi` ( `NId` varchar(100) DEFAULT NULL, `GIR_Id` varchar(20) DEFAULT NULL, `NoIndex` varchar(25) DEFAULT NULL, `Sifat` varchar(25) DEFAULT NULL, `Disposisi` varchar(250) DEFAULT NULL ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
alter table `classification` add column `CIStatus` int(2) DEFAULT NULL after `SusutId`;
alter table `classification` add column `ClStatusParent` int(2) DEFAULT NULL after `CIStatus`;
update classification set CIStatus = 1;
update classification set ClStatusParent = 1;
insert  into `master_gjabatan`(`gjabatanId`,`gjabatanName`) values ('_GenKey_.1','Pimpinan Instansi'),('_GenKey_.2','Eselon I'),('_GenKey_.3','Eselon II'),('_GenKey_.4','Eselon III'),('_GenKey_.5','Eselon IV'),('_GenKey_.6','Unit Kearsipan');
update `groups` set `GroupName` = 'Pejabat Struktural' where `GroupId` = 3;
update `groups` set `GroupName` = 'Sekretaris' where `GroupId` = 4;
alter table `inbox_receiver` add column `status` int(1) NOT NULL default '0' after `To_Id_Desc`;
drop view if exists `v_berkas_aktif`;
drop view if exists `v_berkas_inaktif`;
drop view if exists `v_jejak_surat`;
drop view if exists `v_s_masuk`;
drop view if exists `v_s_masuk_belum_tl`;
CREATE VIEW `v_berkas_aktif` AS (select `r`.`BerkasId` AS `BerkasId`,`r`.`BerkasStatus` AS `BerkasStatus`,`r`.`BerkasNumber` AS `BerkasNumber`,`r`.`RoleId` AS `RoleId`,`e`.`RoleDesc` AS `RoleDesc`,`r`.`BerkasName` AS `BerkasName`,`r`.`BerkasDesc` AS `BerkasDesc`,`r`.`RetensiValue_Active` AS `RetensiValue_Active`,`r`.`RetensiValue_InActive` AS `RetensiValue_InActive` from (`berkas` `r` join `role` `e`) where ((`r`.`RoleId` = `e`.`RoleId`) and (`r`.`BerkasId` <> '1') and (`r`.`RetensiValue_Active` < curdate())));
CREATE VIEW `v_berkas_inaktif` AS (select `r`.`BerkasId` AS `BerkasId`,`r`.`BerkasStatus` AS `BerkasStatus`,`r`.`BerkasNumber` AS `BerkasNumber`,`r`.`RoleId` AS `RoleId`,`e`.`RoleDesc` AS `RoleDesc`,`r`.`BerkasName` AS `BerkasName`,`r`.`BerkasDesc` AS `BerkasDesc`,`r`.`RetensiValue_Active` AS `RetensiValue_Active`,`r`.`RetensiValue_InActive` AS `RetensiValue_InActive` from (`berkas` `r` join `role` `e`) where ((`r`.`RoleId` = `e`.`RoleId`) and (`r`.`BerkasId` <> '1') and (`r`.`RetensiValue_InActive` < curdate())));
CREATE VIEW `v_jejak_surat` AS (select `i`.`NId` AS `NId`,`i`.`Nomor` AS `Nomor`,`rr`.`ReceiveDate` AS `waktu`,`i`.`Hal` AS `Hal`,`i`.`NTipe` AS `NTipe`,`i`.`BerkasId` AS `BerkasId`,`i`.`Tgl` AS `Tgl`,`i`.`NIsi` AS `NIsi`,`i`.`CreatedBy` AS `CreatedBy`,`i`.`CreationRoleId` AS `CreationRoleId`,`rr`.`RoleId_From` AS `RoleId_From`,`rr`.`RoleId_To` AS `RoleId_To`,`rr`.`StatusReceive` AS `StatusReceive`,`rr`.`ReceiverAs` AS `ReceiverAs`,`rr`.`Msg` AS `Msg`,`rr`.`ReceiverAs` AS `tindakan`,`rr`.`RoleId_From` AS `RoleId_From2`,`rr`.`GIR_Id` AS `GIR_Id`,`i`.`InstansiPengirim` AS `InstansiPengirim` from (`inbox` `i` join `inbox_receiver` `rr` on(((`rr`.`NKey` = `i`.`NKey`) and (`rr`.`NId` = `i`.`NId`)))) where (`i`.`NId` is not null));
CREATE VIEW `v_s_masuk` AS (select `i`.`NId` AS `NId`,`i`.`Nomor` AS `Nomor`,`i`.`Hal` AS `Hal`,`i`.`NTipe` AS `NTipe`,`i`.`BerkasId` AS `BerkasId`,`mu`.`UrgensiName` AS `UrgensiName`, `i`.`Tgl` AS `Tgl`,`i`.`NIsi` AS `NIsi`,`i`.`CreatedBy` AS `CreatedBy`,`i`.`CreationRoleId` AS `CreationRoleId`,`rr`.`RoleId_To` AS `RoleId_To`,`rr`.`StatusReceive` AS `StatusReceive`,`i`.`Instansipengirim` AS `InstansiPengirim` from (`inbox` `i` join `inbox_receiver` `rr` on(((`rr`.`NKey` = `i`.`NKey`) and (`rr`.`NId` = `i`.`NId`))) join `master_urgensi` `mu` on `mu`.`UrgensiId` = `i`.`UrgensiId`) where (`i`.`NId` is not null));
CREATE VIEW `v_s_masuk_belum_tl` AS (select `i`.`NId` AS `NId`,`i`.`Nomor` AS `Nomor`,`i`.`Hal` AS `Hal`,`i`.`NTipe` AS `NTipe`,`i`.`BerkasId` AS `BerkasId`,`mu`.`UrgensiName` AS `UrgensiName`, `i`.`Tgl` AS `Tgl`,`i`.`NIsi` AS `NIsi`,`i`.`CreatedBy` AS `CreatedBy`,`i`.`CreationRoleId` AS `CreationRoleId`,`rr`.`RoleId_To` AS `RoleId_To`,`rr`.`StatusReceive` AS `StatusReceive`,`i`.`Instansipengirim` AS `InstansiPengirim` from (`inbox` `i` join `inbox_receiver` `rr` on(((`rr`.`NKey` = `i`.`NKey`) and (`rr`.`NId` = `i`.`NId`))) join `master_urgensi` `mu` on `mu`.`UrgensiId` = `i`.`UrgensiId`) where (`i`.`NId` is not null and `rr`.`status` = '0'));
